### PR TITLE
eaf-pdf-viewer: scroll hooks

### PR DESCRIPTION
**Pull request by c1-g**
This is just #716 without the unrelated commits

### CODE REVIEW

**Comment by manateelazycat** [comment]
what's purpose of this PR?

**Comment by c1-g** [comment]
the hooks `eaf-pdf-scroll-up-hook` / `eaf-pdf-scroll-down-hook` / `eaf-pdf-scroll-left-hook` / `eaf-pdf-scroll-right-hook` is run when pdf-viewer scrolls so you can program them to do whatever you need. 

I'm personally interested in implementing the scroll-up and scroll-down hook to update the modeline of the pdf viewer buffer to show what is the current page I'm reading.

**Comment by manateelazycat** [comment]
> the hooks `eaf-pdf-scroll-up-hook` / `eaf-pdf-scroll-down-hook` / `eaf-pdf-scroll-left-hook` / `eaf-pdf-scroll-right-hook` is run when pdf-viewer scrolls so you can program them to do whatever you need.
> 
> I'm personally interested in implementing the scroll-up and scroll-down hook to update the modeline of the pdf viewer buffer to show what is the current page I'm reading.

I dislike add so many hook just for track current page。

why not add one hook that emit when page render y coordinate changed?

**Comment by manateelazycat** [comment]
> the hooks `eaf-pdf-scroll-up-hook` / `eaf-pdf-scroll-down-hook` / `eaf-pdf-scroll-left-hook` / `eaf-pdf-scroll-right-hook` is run when pdf-viewer scrolls so you can program them to do whatever you need.
> 
> I'm personally interested in implementing the scroll-up and scroll-down hook to update the modeline of the pdf viewer buffer to show what is the current page I'm reading.

I dislike add so many hook just for track current page。

why not add one hook that emit when page render y coordinate changed?

**Comment by c1-g** [comment]
Do you mean on the python side? Is there any function for that? I'll post the mode line idea in Discussion. Closing the PR since there seems to be no need for it.

**Pull request closed without merging**
