### PR TITLE
use mume.js for markdown preview

### PR DESCRIPTION
**Pull request by mackong**
Use mume library for markdown preview, now we support
* kinds of graph with mermaid, plantuml.
* evaluation of code block
* math block
* etc...

see demo.md for actual demo.

more information see https://shd101wyy.github.io/markdown-preview-enhanced/#/.

### CODE REVIEW

**Comment by manateelazycat** [comment]
@mackong When i try demo.md in EAF, file opened, but nothing preview in EAF browser buffer, and Emacs freeze.

I have do "npm install" in EAF after git pull.

**Comment by manateelazycat** [comment]
I just revert this patch. 

Please resend PR if problem fixed.

**Comment by mackong** [comment]
npm install之后预览是正常的吗

**Comment by mackong** [comment]
*eaf*里面有什么报错信息吗

**Comment by manateelazycat** [comment]
> _eaf_里面有什么报错信息吗

没有任何报错，就是直接预览 demo.md 后， 整个Emacs冻结了，看看是不是消息处理或者循环有问题？

**Comment by mackong** [comment]
一个小建议，改动较大的pr, 可以先用git am或者apply来测试，不然merge再revert,git历史有点脏。:smile:

**Pull request merged**
