### PR TITLE
Add refresh command for browser app and prefix app commands like before

### PR DESCRIPTION
**Pull request by clemera**

### CODE REVIEW

**Comment by clemera** [comment]
I included the app name in the prefix, too. For example pdf and browser have different scroll keys so the dummy command needs to distinguish the key it's bound too.

**Comment by MatthewZMD** [comment]
Please check #140

**Comment by clemera** [comment]
Thanks, I missed that and wondered how the prefix vanished ;) Not sure how to deal with this currently.

**Comment by clemera** [comment]
Another benefit of having prefixes is search: When there are many apps you can input `eaf browser` (assuming you use some completion framework) and see all the commands available for the browser app.

**Comment by MatthewZMD** [comment]
Yes I'm sure. We can also make eaf-bind-key smarter, make it recognize variable names with and without prefix. A simple regex would do that.

**Comment by clemera** [comment]
I have added an explanation mentioning the unprefixed name to the dosctring

**Comment by MatthewZMD** [comment]
Great

**Pull request merged**
