### PR TITLE
Map app names to key lists in `eaf-app-binding-alist'

### PR DESCRIPTION
**Pull request by clemera**
This makes it easier to add new apps, one needs to add the app name and the key variable to `eaf-app-binding-alist`, afterwards one just need to create an `eaf-open-<appname>` command.

### CODE REVIEW

**Comment by MatthewZMD** [comment]
Some great refactors!

**Comment by manateelazycat** [comment]
thanks man

**Comment by clemera** [comment]
General question: What about backward incompatible changes? Since this isn't released on a public package repository are you ok with possibly breaking user config?

**Comment by MatthewZMD** [comment]
We could start doing releases and provide CHANGELOG

**Pull request merged**
