### PR TITLE
Add option to control whether override Org store link function for PD…

### PR DESCRIPTION
**Pull request by stardiviner**
This will use docview: link type for EAF opened PDF by default.
Why use this link type by default? Because it's support in Org Mode built-in. And most compatible link type.
Might change this option into a string like "docview", "pdf-tools", "pdfview", etc. But later, I need to thinking.

Thanks for reviewing my PR.

### CODE REVIEW

**Comment by manateelazycat** [comment]
@luhuaei Can you help to review this patch ?

**Comment by luhuaei** [comment]
Thanks cc. Great work @stardiviner :smile:

**Comment by stardiviner** [comment]
😄 I just improved my old code. Seems only me touched my own code. Only me use it...... lonely....

**Comment by MatthewZMD** [comment]
>  I just improved my old code. Seems only me touched my own code. Only me use it...... lonely....

It's good code, I've demo-ed org-store-link at the EmacsConf2020 :)

**Comment by stardiviner** [comment]
I'm happy that you use it. Happyyyy

**Pull request merged**
