### PR TITLE
Add eaf-configure function to configure all relevant app variables

### PR DESCRIPTION
**Pull request by clemera**
Here is an example how one can use it:

    (eaf-configure "browser"
                   :key-alist '(("C-q" . quit-window))
                   :extensions '("xhtml")
                   :display-function* #'switch-to-buffer-other-window)

I hope that matches how you want to approach things in the future. I think one step further would be to use this function to create the settings that exists now and remove the corresponding defcustoms. The idea is to force users to use this function to configure things. This would allow us to easily change implementations/add things in the future without breaking user config, providing a consistent API to configure things. And for new apps we could automatically create the needed variables by deriving their name from the app name. 

What do you think?

### CODE REVIEW

**Comment by manateelazycat** [comment]
> Here is an example how one can use it:
> 
> ```
> (eaf-configure "browser"
>                :key-alist '(("C-q" . quit-window))
>                :extensions '("xhtml")
>                :display-function* #'switch-to-buffer-other-window)
> ```
> 
> I hope that matches how you want to approach things in the future. I think one step further would be to use this function to create the settings that exists now and remove the corresponding defcustoms. The idea is to force users to use this function to configure things. This would allow us to easily change implementations/add things in the future without breaking user config, providing a consistent API to configure things. And for new apps we could automatically create the needed variables by deriving their name from the app name.
> 
> What do you think?

First, thanks for this patch.

IMO, I think best software is out of box and user don't need configure anything.
User only need use it directly after install EAF.

eaf-configure is a developer's perspective that provide flexible interface to user for customize, just like package.el does.

I agree we should provide standard and stable APIs for customize, but eaf-configure make thing more complicated.

From user perspective, the only thing I need is keybinding of EAF applicaiton, I don't care any other option, such as ```extensions```, ```display-function``` ,
these are all looking to good, but for users who value a very small thing.

**Comment by manateelazycat** [comment]
Maybe I am old-school emacser, I am very afraid if I need read many document to customize something.

I prefer when you need to customize something, you can just write one line configure to customize it,
rather than to study various variables of this function,
eaf-configure looked really like helm's customize interface,
the first impression is too complicated.

Above is my point, welcome to discuss.

**Comment by clemera** [comment]
>  I think best software is out of box and user don't need configure anything

I totally agree with that. The reason I wrote `eaf-configure` is mostly for convenience to customize things if you need to, which shouldn't be the standard case because hopefully we have configured things to match users expectations. 

The problem I see with the current approach is that it's hard for the user to know which variable to customize. He has to know that he has to search for `eaf-browser-keybinding` to change keybindings, see [here](https://github.com/manateelazycat/emacs-application-framework/pull/149#issuecomment-565261072) for example. For bookmarks would have to find `eaf-app-bookmark-handlers-alist` and so on.

The idea with `eaf-configure` was to have a single entry point so the user can read its docstring to see how to customize any setting he cares about. 

> I am very afraid if I need read many document to customize something

That is a good point, it is good if things work just the usual Emacs way. We can also keep things as they are and only provide `eaf-configure` for additional convenience.

**Comment by clemera** [comment]
Another idea I have would be to have a command like `eaf-customize-app-setting` which would query for the app name and then for the setting you want to customize and after that open a customize buffer for that setting.

**Comment by manateelazycat** [comment]
> > I think best software is out of box and user don't need configure anything
> 
> I totally agree with that. The reason I wrote `eaf-configure` is mostly for convenience to customize things if you need to, which shouldn't be the standard case because hopefully we have configured things to match users expectations.
> 
> The problem I see with the current approach is that it's hard for the user to know which variable to customize. He has to know that he has to search for `eaf-browser-keybinding` to change keybindings, see [here](https://github.com/manateelazycat/emacs-application-framework/pull/149#issuecomment-565261072) for example. For bookmarks would have to find `eaf-app-bookmark-handlers-alist` and so on.
> 
> The idea with `eaf-configure` was to have a single entry point so the user can read its docstring to see how to customize any setting he cares about.
> 
> > I am very afraid if I need read many document to customize something
> 
> That is a good point, it is good if things work just the usual Emacs way. We can also keep things as they are and only provide `eaf-configure` for additional convenience.

Example, currently ```eaf-app-display-function-alist`` just support markdown-previewer and org-previewer, other EAF application don't need care display function.
If user found option ```display-function``` option in eaf-configure, it's hard to understand "What is display function use for?" and "Why other EAF application don't need display function?"

Another situation, ```eaf-app-bookmark-handlers-alist`` should be internal variable for simple code, user should not care about it.

My point is:

1. For user, user only care about keybinding of EAF application.
2. For hacker, they know how to cusotmize EAF through read source code.
3. If we agree "out of box" principle, user don't need read so many docstring even document is very detailed, less is more.

You and me is developer, eaf-configure maybe better for developer, but it's too complicated for user,
I can not imagine what the user needs to customize addition to custom shortcuts?

**Comment by clemera** [comment]
Okay, I understand that your intention is to support the most common use case best, maybe it's enough to improve `eaf-bind-key` (to require the app name not the keybinding list variable name) and to add an additional `eaf-bind-keys` to bind multiple keys at once.

**Comment by MatthewZMD** [comment]
I agree with Andy that this function is too complicated from the user's perspective. For example, I don't really understand why would a user ever want to mess around with `eaf-app-display-function-alist` or `eaf-app-bookmark-handlers-alist` or `eaf-app-display-function-alist`.

>  use this function to create the settings that exists now and remove the corresponding defcustoms.

While realizing this is too complicated for a user, it might actually a good fit for internal use. We can tidy a lot of code.

**Comment by MatthewZMD** [comment]
> improve eaf-bind-key (to require the app name not the keybinding list variable name) and to add an additional eaf-bind-keys to bind multiple keys at once.

This is a great idea, welcome to PR

**Comment by clemera** [comment]
> why would a user ever want to mess around with eaf-app-display-function-alist

To display the app buffer in other window user might want to use `switch-buffer-other-window`, but if you both feel it shouldn't be included that's fine. You can close this or if you like include it only for internal use.

**Comment by clemera** [comment]
> This is a great idea, welcome to PR

I think maybe `eaf-bind-key` should stay as it is to not break existing config. And then add an additional `eaf-bind-keys` which has these features?

**Comment by MatthewZMD** [comment]
Now thinking of it again, the user really has no idea what `app-name` really is unless they open up the source code. While they can figure out what `eaf-.*-keybinding` by doing `C-h v` (assuming they have a completion framework)

**Comment by MatthewZMD** [comment]
> if you like include it only for internal use.

There is no need to close it right now, let's wait until Andy wakes up to see if he wants it to be for internal use only. You can continue to commit and let us have an idea to what might look like when its fully geared toward internal use

**Comment by clemera** [comment]
> Now thinking of it again, the user really has no idea what app-name really is unless they open up the source code. While they can figure out what eaf-.*-keybinding

Yes, but in this case they have to know to search for "...keybinding" which is not a standard Emacs term. Maybe we should use standard keymaps named `eaf-browser-map` and such. This way the user would find all relevant maps by searching for eaf.*map which would be nice and they could also use whatever they use to bind keys and we don't have to reinvent the wheel ;)

**Comment by MatthewZMD** [comment]
> Maybe we should use standard keymaps named eaf-browser-map and such. This way the user would find all relevant maps by searching for eaf.*map which would be nice and they could also use whatever they use to bind keys and we don't have to reinvent the wheel ;)

Sounds fair, but please resist from making big changes until I finish refactoring and get a PR from Stefan Monnier in, to reduce the amount of possible code conflicts ;)

**Comment by clemera** [comment]
Thanks for the warning, I will wait :) Nice that Stefan has interest in this project he is an Emacs legend.

**Comment by manateelazycat** [comment]
> > why would a user ever want to mess around with eaf-app-display-function-alist
> 
> One use case might be to display the app buffer in other window then the user can use `switch-buffer-other-window`, if you both feel it shouldn't be included that's fine. You can close this or if you like include it only for internal use.

It's hacker perspective, they will figure out how to customize this after read source code.

**Comment by manateelazycat** [comment]
> Now thinking of it again, the user really has no idea what `app-name` really is unless they open up the source code. While they can figure out what `eaf-.*-keybinding` by doing `C-h v` (assuming they have a completion framework)

We have write docs about keybinding in KEYBINDING.md, user don't need read source code

**Comment by manateelazycat** [comment]
> > Now thinking of it again, the user really has no idea what app-name really is unless they open up the source code. While they can figure out what eaf-.*-keybinding
> 
> Yes, but in this case they have to know to search for "...keybinding" which is not a standard Emacs term. Maybe we should use standard keymaps named `eaf-browser-map` and such. This way the user would find all relevant maps by searching for eaf.*map which would be nice and they could also use whatever they use to bind keys and we don't have to reinvent the wheel ;)

We can write those in document, document is enough. ;)

**Comment by manateelazycat** [comment]
> > if you like include it only for internal use.
> 
> There is no need to close it right now, let's wait until Andy wakes up to see if he wants it to be for internal use only. You can continue to commit and let us have an idea to what might look like when its fully geared toward internal use

Hi, thanks for recently contribution, really.

But I dislike complicated code, I think simple always good, not only for users, developers is the same.

If project is out of the box, user will grow up.
If code is simple enough, more hackers will join us. ;)

I need close this PR now, sorry.

**Comment by MatthewZMD** [comment]
> Thanks for the warning, I will wait :) Nice that Stefan has interest in this project he is an Emacs legend.

Done :)

**Comment by clemera** [comment]
> We can write those in document, document is enough. ;)

Users don't always read documents too ;) Currently they need to figure out three things:

1. How to bind a key
2. How to use `eaf-bind-key`
2. How is the key binding variable name for the app

When a new app is added we have to make sure that we don't forget to document the variable name, too. When we would use normal keymaps most user would now how to use `define-key` or could continue to use any packages which simplfy key bindings like `bind-key`. They still would have to figure out the map name but most Emacs users would assume to find keybindings in something like "eaf-..-map" variables. What do you think, if you give an OK I will implement it ;)

**Comment by MatthewZMD** [comment]
> What do you think, if you give an OK I will try to implement it ;)

I just discussed with Andy, yes you can start implementing this feature :)

**Pull request closed without merging**
