### PR TITLE
Make window-combination-resize setq-local

### PR DESCRIPTION
**Pull request by MatthewZMD**
@clemera I saw your FIXME regarding `(setq window-combination-resize t)`. Would `setq-local` fix this problem?

### CODE REVIEW

**Comment by clemera** [comment]
I'm not sure what the reason is to set this setting. Making it buffer local means it only applies when splitting windows from the eaf buffer. This does not change the global user setting so this would fix the problem of changing the potentially unwanted splitting behavior. But maybe it can be removed completely?

**Comment by MatthewZMD** [comment]
@manateelazycat

**Comment by manateelazycat** [comment]
> I'm not sure what the reason is to set this setting. Making it buffer local means it only applies when splitting windows from the eaf buffer. This does not change the global user setting so this would fix the problem of changing the potentially unwanted splitting behavior. But maybe it can be removed completely?

The reason is that the very beginning, if not so set, the more points the smaller the window, the window is too small, EAF would not be able to use, such as the browser.

**Comment by MatthewZMD** [comment]
Yes, so the problem right now is EAF changes global user setting. Shall we change it to `setq-local`?

**Pull request merged**
