### PR TITLE
Refactor emacs hook usage

### PR DESCRIPTION
**Pull request by clemera**
Before adding hooks was done when loading the package now it only happens when starting an app. I also made hooks buffer local where possible.

One thing I noticed when testing this is that org-preview does not sync but that problem existed before. It saves on export but the updated file is not displayed for some reason.

### CODE REVIEW

**Comment by manateelazycat** [comment]
Thanks

**Comment by clemera** [comment]
@manateelazycat I noticed org-preview does not sync the view on save:

    (eaf-call "update_buffer_with_url" "app.orgpreviewer.buffer" (buffer-file-name) "")

Seems to fail, but I'm not sure why

**Comment by manateelazycat** [comment]
i dont use org mode

**Comment by clemera** [comment]
Okay, I will try to investigate

**Pull request merged**
