### PR TITLE
Refactor pdf-viewer

### PR DESCRIPTION
**Pull request by luhuaei**
Current determine refactor to `PdfPage`, `PdfDocument`, `PdfAnnotate`

- [ ] PdfDocument
- [ ] PdfPage
- [ ] PdfAnnotate

Each steps purpose in commit message, If you feel hard to understand or unreasonable, comment on below.

### CODE REVIEW

**Review by luhuaei — COMMENTED** [review]
> typo: I understand the loop for imagelist.

I don't understand the loop for imagelist. :smile_cat:

**Comment by manateelazycat** [comment]
patch is stable？if so，i will merge immediately

**Comment by luhuaei** [comment]
> patch is stable？if so，i will merge immediately

Stable, I test no break existing function.

**Comment by manateelazycat** [comment]
> > patch is stable？if so，i will merge immediately
> 
> Stable, I test no break existing function.

awesome，给你点赞

**Pull request merged**
