### PR TITLE
allow user set where store cache files

### PR DESCRIPTION
**Pull request by ctrl2wei**

### CODE REVIEW

**Comment by MatthewZMD** [comment]
Maybe name it something other than cache files, because it is not just cache.

**Comment by ctrl2wei** [comment]
> Maybe name it something other than cache files, because it is not just cache.

I have no idea how to name it. I just don't want it in my configuration directory.

**Comment by MatthewZMD** [comment]
No worries. Please change it to eaf-config-location

**Comment by MatthewZMD** [comment]
LGTM, thanks for the patch!

**Pull request merged**
