### PR TITLE
Changes: Code refactor, fix bugs, better eaf-open-browser, fix grammar, documentation, etc.

### PR DESCRIPTION
**Pull request by MatthewZMD**
I made numerous improvements in this PR:
1. Better naming convention: 
- `eaf-open-url` -> `eaf-open-browser`
  - Emphasize the `url` is a browser URL, stay consistent with `app-name` too
- `markdownpreviewer` -> `markdown-previewer`, `videoplayer` -> `video-player`, etc...
  - Naming consistency
- `eaf-show-file-qrcode` -> `eaf-file-sender-qrcode`, `eaf-air-share` -> `eaf-file-transfer-air-share`, etc...
  - Naming consistency to emphasize EAF is dealing with file transfer
- `filetransfer` -> `file-sender` and `fileuploader` -> `file-receiver`
  - Reduce ambiguity
2. Add `(equal key-desc "SPC")`, need to recognize SPC in EAF
3. Create `eaf-open-demo`, `eaf-open-camera`, `eaf-open-qutebrowser` functions. 

Take out:
```
(cond ((string-equal url "eaf-demo")
           (setq app-name "demo"))
          ((string-equal url "eaf-camera")
           (setq app-name "camera"))
          ((string-equal url "eaf-qutebrowser")
           (setq app-name "qutebrowser"))
```
Because
- `eaf-open` is `interactive "F`. It is impossible to pass `url` as `"eaf-demo"` or `"eaf-camera"` or `"eaf-qutebrowser"` interactively when using `counsel`. It only accepts a valid file as input.
- To stay consistent with the function `eaf-open-url` (or the new name `eaf-open-browser`). It makes sense to use special functions when achieving special goals, just like opening a browser. Normal file interactions stay with `eaf-open`.
4. Rewrite
```
((and (not (string-prefix-p "/" url))
                (not (string-prefix-p "~" url))
                (string-match thing-at-point-short-url-regexp url))
           (setq app-name "browser")
           (unless (string-prefix-p "http" url)
             (setq url (concat "http://" url)))
```
and put in the funcion `eaf-open-browser`.
- It makes sense to validate the URL legitimacy when opening EAF browser only. As mentioned above, the current `interactive "F"` in `eaf-open` can only open a file interactively. We don't need to worry about validating browser URL in `eaf-open`.
- Replace `thing-at-point-short-url-regexp` with `"^\\(https?:\/\/\\)?[a-z0-9]+\\([\-\.]\\{1\\}[a-z0-9]+\\)*\.[a-z]\\{2,5\\}\\(:[0-9]{1,5}\\)?\\(\/.*\\)?$"`, it's a better regex that validates URL legitimacy more accurately.
5. Fix grammatical errors
6. Add a lot of documentations
7. Better eaf-find-alternate-file-in-dired
- It will allow better navigating and opening files using EAF through the dired buffer
8. Rename air-share to airshare
9. Better buffer name using the actual file name instead of a truncated file path, which *most* of the times will cut off parts of the file.
10. Qt.Key_K -> Qt.Key.Key_K, etc. in `pdf-viewer/buffer.py`. This is according to QtCore

### CODE REVIEW

**Comment by MatthewZMD** [comment]
More changes:
1. Better eaf-find-alternate-file-in-dired
- It will allow better navigating and opening files using EAF through the dired buffer
2. Rename air-share to airshare
3. Better buffer name using the actual file name instead of a truncated file path, which *most* of the times will cut off parts of the file.

**Comment by manateelazycat** [comment]
@MatthewZMD Thanks for patch, sorry i haven't time play EAF recently, because i haven't Linux device.

Sorry about that.

**Comment by MatthewZMD** [comment]
That's alright. Since I use EAF daily, I will continue to improve and push into my forked repo, and I will try my best to maintain a list of changes here. So when you are ready to merge this PR, you can reference this list.

**Comment by MatthewZMD** [comment]
Rename `filetransfer` -> `file-sender` and `fileuploader` -> `file-receiver` to reduce ambiguity

**Comment by manateelazycat** [comment]
@MatthewZMD 你能把这个补丁拆分一下吗？

每个补丁只有一个功能，而不是让一个补丁包含各种各样不同的补丁。

而且我建议你先发一些功能提升的补丁，重命名的补丁先不要发，等我们把功能性的补丁都测试合并以后再做重命名的补丁。

非常感谢你的补丁，但是这个补丁太大了，不适合直接合并和测试，请把补丁打散以后再次提交，谢谢

**Comment by MatthewZMD** [comment]
哈哈哈，你终于有时间看了！

可以，我回头拆一拆

**Comment by manateelazycat** [comment]
> 哈哈哈，你终于有时间看了！
> 
> 可以，我回头拆一拆

哈哈哈哈，我最近终于从Mac回到Linux了，欢迎继续贡献你的补丁吧，期待！

**Pull request closed without merging**
